# Site settings
title: BinaryAbacus
email: felixlaumon@gmail.com
description: >
  BinaryAbacus.io is a data visualization blog devoted to telling stories in Asia with hard numbers and interactive charts.
baseurl: ""
url: "http://www.binaryabacus.io"
permalink: none
comments: true

paginate: 1

# Build settings
markdown: kramdown
